// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `instance`, `proxy_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProxyState`

/// Connect to a remote iroh-ssh endpoint.
/// Returns the local TCP port to connect an SSH client to.
Future<int> connectIroh({required String endpointId}) =>
    RustLib.instance.api.crateApiSimpleConnectIroh(endpointId: endpointId);

/// Disconnect and clean up.
Future<void> disconnectIroh() =>
    RustLib.instance.api.crateApiSimpleDisconnectIroh();

/// Check if currently connected. Returns the local proxy port if connected.
int? getProxyPort() => RustLib.instance.api.crateApiSimpleGetProxyPort();
