// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Connect to a remote iroh-ssh endpoint.
/// Returns the local TCP port to connect an SSH client to.
///
/// `relay_urls` replaces the default relay servers; `extra_relay_urls` adds alongside them.
/// Pass empty vectors to use defaults.
Future<int> connectIroh({
  required String endpointId,
  required List<String> relayUrls,
  required List<String> extraRelayUrls,
}) => RustLib.instance.api.crateApiSimpleConnectIroh(
  endpointId: endpointId,
  relayUrls: relayUrls,
  extraRelayUrls: extraRelayUrls,
);

/// Disconnect a connection by its port.
Future<void> disconnectIroh({required int port}) =>
    RustLib.instance.api.crateApiSimpleDisconnectIroh(port: port);

/// Disconnect all active connections.
Future<void> disconnectAll() =>
    RustLib.instance.api.crateApiSimpleDisconnectAll();

/// Get the number of active connections.
Future<BigInt> connectionCount() =>
    RustLib.instance.api.crateApiSimpleConnectionCount();

/// Query connection info for an active connection by its port.
/// Returns `None` if no iroh connection has been established yet.
Future<IrohConnectionInfo?> connectionInfo({required int port}) =>
    RustLib.instance.api.crateApiSimpleConnectionInfo(port: port);

class IrohConnectionInfo {
  final bool isDirect;
  final bool isRelay;
  final String? relayUrl;
  final double? latencyMs;

  const IrohConnectionInfo({
    required this.isDirect,
    required this.isRelay,
    this.relayUrl,
    this.latencyMs,
  });

  @override
  int get hashCode =>
      isDirect.hashCode ^
      isRelay.hashCode ^
      relayUrl.hashCode ^
      latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IrohConnectionInfo &&
          runtimeType == other.runtimeType &&
          isDirect == other.isDirect &&
          isRelay == other.isRelay &&
          relayUrl == other.relayUrl &&
          latencyMs == other.latencyMs;
}
